# Generated by Django 5.0 on 2023-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contacto',
            field=models.EmailField(default='Coloque gmail de contacto', max_length=254),
        ),
        migrations.AlterField(
            model_name='store',
            name='nombre',
            field=models.CharField(default='Coloque nombre empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='ubicacion',
            field=models.CharField(blank=True, default='Coloque ubicacion empresa', max_length=150, null=True),
        ),
    ]
